### ISSUE TITLE
About the setting of learning_rate

### ISSUE THREAD

**Issue by mia-7** [ManiadisG/DivClust#3]
Hello,
    From the main.py, the learning_rate is set as 0.0003 and the optimizer is the Adam. However, I notice that there is the setting about lr_schedule in main_config.yaml. And it seems to be not used in the main.py. Could you tell me the optimizer and learning_rate setting in your project? Thanks for your time.

**Comment by ManiadisG** [comment]
Hi!
You are right and you can ignore the lr_schedule argument. It was one of the things I tried but I ended up keeping the settings of the original papers for CC and PICA, which have a fixed lr. I just forgot to remove the argument. Thanks for pointing this out!

**Comment by mia-7** [comment]
I get it. Thank you for your apply.
